# Generated by Django 4.2.5 on 2023-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=320)),
                ('phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
